# Generated by Django 2.2.8 on 2020-01-04 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('createdon', models.DateTimeField(auto_now_add=True)),
                ('lastupdatedon', models.DateTimeField(auto_now=True)),
                ('lastupdatedby', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(help_text='Country name', max_length=100, unique=True)),
                ('createdby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
    ]
