# Generated by Django 2.2.9 on 2020-02-04 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('city_history', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('createdon', models.DateTimeField(auto_now_add=True)),
                ('lastupdatedon', models.DateTimeField(auto_now=True)),
                ('lastupdatedby', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(help_text='State name', max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city_history.Country')),
                ('createdby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'States',
                'unique_together': {('country', 'name')},
            },
        ),
    ]
